---
title: "yelp-regression"
author: "Lanxi Zhang"
date: "12/2/2023"
output: html_document
---

```{r}
library(dplyr)
```

```{r, eval=FALSE}
library(dplyr)
alldata <- read.csv("alldata.csv")

convert_na_or_empty_to_zero <- function(x) {
  ifelse(is.na(x) | x == "", 0, x)
}

alldata1 <- alldata %>%
  mutate_all(convert_na_or_empty_to_zero)

# print(alldata1)
```
```{r, eval=FALSE}
convert_true_tt <- function(x) {
  ifelse(x=="u'free'"|x=="'free'", 2, x)
}

# 应用转换函数到所有列
alldata2 <- alldata1 %>%
  mutate_all(convert_true_tt)

```


```{r, eval=FALSE}
convert_logical_to_numeric <- function(x) {
  ifelse(x == 'True'|x== 'yes_corkage'|x=="'casual'"|x=="u'casual'"|x=="'yes_corkage'"|x=="u'quiet'"|x=="u'full_bar'"|x=="'full_bar'"|x=="u'paid'", 1, ifelse(x == 'False'|x=="'dressy'"|x=="u'dressy'"|x=="u'average'"|x=="'none'"|x=="u'none'"|x=="None"|x=="u'no'"|x=="'no'", 0, x))
}

alldata2 <- alldata2 %>%
  mutate_all(convert_logical_to_numeric)

# print(alldata2)
# alldata2 %>%  View()
```

```{r, eval=FALSE}
alldata3 <- alldata2 %>%
  mutate(
    attributes.WheelchairAccessible = as.integer(attributes.WheelchairAccessible),
    attributes.BikeParking = as.integer(attributes.BikeParking),
    attributes.ByAppointmentOnly = as.integer(attributes.ByAppointmentOnly),
    attributes.DogsAllowed = as.integer(attributes.DogsAllowed),
    attributes.GoodForKids = as.integer(attributes.GoodForKids),
    attributes.BusinessAcceptsCreditCards = as.integer(attributes.BusinessAcceptsCreditCards),
    attributes.WiFi = as.integer(attributes.WiFi),
    attributes.RestaurantsPriceRange2 = as.integer(attributes.RestaurantsPriceRange2),
    attributes.BusinessAcceptsBitcoin = as.integer(attributes.BusinessAcceptsBitcoin),
    attributes.OutdoorSeating = as.integer(attributes.OutdoorSeating),
    attributes.Alcohol = as.integer(attributes.Alcohol),
    attributes.RestaurantsReservations = as.integer(attributes.RestaurantsReservations),
    attributes.Caters = as.integer(attributes.Caters),
    attributes.RestaurantsTakeOut = as.integer(attributes.RestaurantsTakeOut),
    attributes.NoiseLevel = as.integer(attributes.NoiseLevel),
    attributes.HasTV = as.integer(attributes.HasTV),
    attributes.RestaurantsDelivery = as.integer(attributes.RestaurantsDelivery),
    attributes.RestaurantsAttire = as.integer(attributes.RestaurantsAttire),
    attributes.RestaurantsGoodForGroups = as.integer(attributes.RestaurantsGoodForGroups),
    attributes.HappyHour = as.integer(attributes.HappyHour),
    attributes.Corkage = as.integer(attributes.Corkage),
    attributes.BYOBCorkage = as.integer(attributes.BYOBCorkage),
    
    attributes.RestaurantsTableService = as.integer(attributes.RestaurantsTableService),
    attributes.AcceptsInsurance = as.integer(attributes.AcceptsInsurance)
    
  )


# summary(alldata3)
# write.csv(alldata3, "cleandata.csv")
```


```{r}
alldata3 <- read.csv("cleandata.csv")
regression <- lm(stars_business 
                 ~ `attributes.WheelchairAccessible`
                 +`attributes.BikeParking`
                 +attributes.ByAppointmentOnly
                 +attributes.DogsAllowed
                 +attributes.GoodForKids
                 +attributes.BusinessAcceptsCreditCards
                 +attributes.WiFi
                 +attributes.RestaurantsPriceRange2
                 +attributes.BusinessAcceptsBitcoin
                 +attributes.OutdoorSeating
                 +attributes.Alcohol
                 +attributes.RestaurantsReservations
                 +attributes.NoiseLevel
                 +attributes.HasTV
                 +attributes.RestaurantsDelivery
                 +attributes.RestaurantsAttire
                 +attributes.RestaurantsGoodForGroups
                 +attributes.HappyHour
                 +attributes.Corkage
                 +attributes.BYOBCorkage
                 +attributes.RestaurantsTableService
                 +attributes.AcceptsInsurance
                 
                 +Population.Staying.at.Home
                 +Population.Not.Staying.at.Home
                 +Number.of.Trips, data = alldata3)
summary(regression)
```




```{r}
step_regression <- step(regression, direction = "both")

# 显示最终模型的摘要
summary(step_regression)
```

























